### ISSUE TITLE
An issue when downloading multiple episodes with legacy player

### ISSUE THREAD

**Issue by Abu3safeer** [DasKraken/CR-dl#35]
Hello everyone.

I would like to thank @DasKraken for building this awesome app.

As everyone knows that CR-dl can download multiple episodes in just one command, 
but trying to download more than one episode at a time "WITH --legacyPlayer " resulting to an issue:
![image](https://user-images.githubusercontent.com/12091003/72608460-c5086b00-3933-11ea-8d22-6f3f8def5fe9.png)

```javascript
{ 
  body: 'error code: 1005',
  status: 403,
  statusText: 'Forbidden',
  url:
   'http://www.crunchyroll.com/xml/?req=RpcApiSubtitle_GetXml&subtitle_script_id=108507' 
}
```

you can produce this with this command:
download -l "arME"  -c "5" --maxAttempts "5" --attachFonts --legacyPlayer -o "{seasonTitle} - {episodeNumber} [{resolution}].mkv" "https://www.crunchyroll.com/ar/jojos-bizarre-adventure/" "1080p"

**Comment by Abu3safeer** [comment]
Hello @DasKraken ,
I noticed that you removed --legacyPlayer in version 4.0.0, is it just because of this issue? or something else happened? 

Because I need this feature, it is very useful for shows published in flash player era.

**Comment by DasKraken** [comment]
Not only this but I don't see any reason to keep maintaining that feature. Besides that it was using the package [crunchyroll-lib](https://www.npmjs.com/package/crunchyroll-lib) that isnt updated and is now even removed from github, keeping getting more and more broken due to changes at crunchyroll.

If you need this feature, feel free to use the older version.

**Comment by Abu3safeer** [comment]
A dependency issue, I understand now.
Thanks for clarifying the reason.
